# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: default-deny-ingress
# spec:
#   podSelector: {}
#   policyTypes:
#   - Ingress
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: allow-policy
# spec:
#   podSelector: {}
#   ingress:
#     - from:
#       - podSelector:
#           matchLabels:
#             deployment: default
#       ports:
#       - protocol: TCP
#         port: 80
#   policyTypes:
#   - Ingress
