apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ubuntu-default
  labels:
    app:  ubuntu-default
spec:
  selector:
    matchLabels:
      app: ubuntu-default
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  ubuntu-default
        deployment: default
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  ubuntu-default
        image:  ubuntu:latest
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do echo 'Hello Bro' && sleep 30; done;"]
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
        - containerPort:  80
      restartPolicy: Always 
