apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ubuntu
  namespace: default
  labels:
    app:  ubuntu
spec:
  selector:
    matchLabels:
      app: ubuntu
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  ubuntu
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  ubuntu
        image:  ubuntu:latest
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  ubuntu
      restartPolicy: Always 
