---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
        version: v1
    spec:
      containers:
      - name: whereami
        image: us-docker.pkg.dev/google-samples/containers/gke/whereami:v1.2.20
        env:
        - name: METADATA
          value: "foo"
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: foo
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: foo
  ports:
  - port: 8080
    targetPort: 8080
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: site-whereami-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - kind: Gateway
    name: internal-whereami-gateway
  hostnames:
  - "whereami.example.com"
  rules:
  - backendRefs:
    - name: foo
      port: 8080
